# Build and deploy Docker app to Azure Web App via ACR
name: Build and deploy Docker app to Azure Web App - hgs-refuce-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hgs-refuce-backend:${{ github.sha }} \
                       -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/hgs-refuce-backend:latest .

      - name: Login to ACR
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_LOGIN_SERVER }}

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hgs-refuce-backend:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/hgs-refuce-backend:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hgs-refuce-backend-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7DA74FA0B2464B909857CE6F17C0B8A9 }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/hgs-refuce-backend:latest
